codecov:
  allow_coverage_offsets: true

parsers:
  go:
    partials_as_hits: true 

coverage:
  precision: 1
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: auto
        threshold: 1%
        if_not_found: success
        if_ci_failed: error
    patch:
      default: false
    changes:
      default: false

comment:
  behavior: default
  show_carryforward_flags: true

github_checks:
  annotations: true
